# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingressClass: kr-nginx
Backend:
  replicaCount: 1
  image:
    repository: ccr.ccs.tencentyun.com/trial/backend
    tag: "20220214-demo3"

Frontend:
  replicaCount: 1
  image: 
    repository: ccr.ccs.tencentyun.com/trial/frontend
    tag: "202120214-demo1"

domain: demo.domain.com
port: 20219

registrySecret: ""
